version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8089:80"
    depends_on:
      - web

  web:
    image: golang:latest
    working_dir: /app
    volumes:
      - ./web:/app
    ports:
      - "8080:8080"
    command: go run main.go 

  apache:
    image: httpd:latest
    ports:
      - "8081:80"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"